// DO NOT EDIT - AUTOGENERATED



const components: { [key: string]: any } = {

}

const getVisualizationComponent = (year: number, day: number) => {
  return components[`vis${year}_${day.toString().padStart(2, '0')}`]
}

export default getVisualizationComponent
  
  